# Generated by Django 5.0 on 2026-04-29 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='businesses.business'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['business'], name='users_busines_285d23_idx'),
        ),
    ]
