# Generated by Django 5.0 on 2026-04-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_name',
            field=models.CharField(blank=True, help_text="Name of the discount (e.g., 'Sale 20%')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Automatic discount percentage (0‑100)', max_digits=5),
        ),
    ]
