# Generated by Django 5.0 on 2026-05-05 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_discount_name_product_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='pack_size',
            field=models.IntegerField(default=1, help_text='Number of pieces in one carton'),
        ),
    ]
